/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import com.sun.awt.AWTUtilities;
import java.awt.Image;
import java.awt.Shape;
import java.awt.Toolkit;
import java.awt.geom.RoundRectangle2D;
import javax.swing.JFrame;

/**
 *
 * @author danlo
 */
public class FrmLogin extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public FrmLogin() {
        initComponents();
         this.setLocationRelativeTo(null); 
         Shape forma= new RoundRectangle2D.Double(0,0, this.getBounds() .width, this.getBounds() .height,40,40);
         AWTUtilities. setWindowShape(this, forma);
         setIconImage(Logo());
    }
public Image Logo(){
    Image retvalue=Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Recursos_Proyecto/B&G Morado 2.png"));
    return retvalue;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondo = new Controles_Personalizados.Paneles.PanelRound();
        PanelContenedorCampos = new Controles_Personalizados.Paneles.PanelRound();
        LogoLogin = new javax.swing.JLabel();
        txtcontra = new Controles_Personalizados.textfields.PasswordField();
        txtusuario = new Controles_Personalizados.textfields.TextField();
        btnConocerMas = new Controles_Personalizados.Botones.ButtonGradient();
        btnLogin = new Controles_Personalizados.Botones.ButtonGradient();
        lblOlvide = new javax.swing.JLabel();
        textologin = new javax.swing.JLabel();
        ImagenLogin = new javax.swing.JLabel();
        btnMinimizar = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelFondo.setBackground(new java.awt.Color(42, 36, 56));
        PanelFondo.setPreferredSize(new java.awt.Dimension(1366, 768));
        PanelFondo.setRoundBottomLeft(35);
        PanelFondo.setRoundBottomRight(40);
        PanelFondo.setRoundTopLeft(35);
        PanelFondo.setRoundTopRight(40);
        PanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelContenedorCampos.setBackground(new java.awt.Color(254, 254, 254));
        PanelContenedorCampos.setPreferredSize(new java.awt.Dimension(629, 768));
        PanelContenedorCampos.setRoundBottomLeft(35);
        PanelContenedorCampos.setRoundTopLeft(35);
        PanelContenedorCampos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/LogoB&GLogin.png"))); // NOI18N
        PanelContenedorCampos.add(LogoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        txtcontra.setBackground(new java.awt.Color(254, 254, 254));
        txtcontra.setForeground(new java.awt.Color(42, 36, 56));
        txtcontra.setCaretColor(new java.awt.Color(42, 36, 56));
        txtcontra.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        txtcontra.setLabelText("Contraseña");
        txtcontra.setLineColor(new java.awt.Color(42, 36, 56));
        txtcontra.setSelectionColor(new java.awt.Color(58, 50, 75));
        txtcontra.setShowAndHide(true);
        PanelContenedorCampos.add(txtcontra, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 450, 70));

        txtusuario.setBackground(new java.awt.Color(254, 254, 254));
        txtusuario.setForeground(new java.awt.Color(42, 36, 56));
        txtusuario.setCaretColor(new java.awt.Color(42, 36, 56));
        txtusuario.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        txtusuario.setLabelText("Usuario");
        txtusuario.setLineColor(new java.awt.Color(42, 36, 56));
        txtusuario.setSelectionColor(new java.awt.Color(58, 50, 75));
        PanelContenedorCampos.add(txtusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 450, 70));

        btnConocerMas.setBackground(new java.awt.Color(254, 254, 254));
        btnConocerMas.setForeground(new java.awt.Color(42, 36, 56));
        btnConocerMas.setText("Conocer mas...");
        btnConocerMas.setColor1(new java.awt.Color(239, 239, 239));
        btnConocerMas.setColor2(new java.awt.Color(239, 239, 239));
        btnConocerMas.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        PanelContenedorCampos.add(btnConocerMas, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 710, 170, -1));

        btnLogin.setBackground(new java.awt.Color(254, 254, 254));
        btnLogin.setText("Iniciar Sesion");
        btnLogin.setColor1(new java.awt.Color(42, 36, 56));
        btnLogin.setColor2(new java.awt.Color(58, 50, 75));
        btnLogin.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        PanelContenedorCampos.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 500, 320, -1));

        lblOlvide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/Olvidaste tu contraseña_.png"))); // NOI18N
        lblOlvide.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblOlvide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOlvideMouseClicked(evt);
            }
        });
        PanelContenedorCampos.add(lblOlvide, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, -1, -1));

        textologin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/TextoLogin.png"))); // NOI18N
        PanelContenedorCampos.add(textologin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 710, -1, -1));

        PanelFondo.add(PanelContenedorCampos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 760));

        ImagenLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/imagenlogin.png"))); // NOI18N
        PanelFondo.add(ImagenLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 120, -1, -1));

        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/Maximizar.png"))); // NOI18N
        btnMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseClicked(evt);
            }
        });
        PanelFondo.add(btnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 20, -1, -1));

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/CerrarLogin.png"))); // NOI18N
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCerrarMousePressed(evt);
            }
        });
        PanelFondo.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 20, -1, -1));

        getContentPane().add(PanelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        FrmDashboard rec = new FrmDashboard();
        rec.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void lblOlvideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOlvideMouseClicked
        // TODO add your handling code here:
        MenuRecu rec = new MenuRecu();
        rec.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblOlvideMouseClicked

    private void btnCerrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMousePressed
        System.exit(0);
    }//GEN-LAST:event_btnCerrarMousePressed

    private void btnMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btnMinimizarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImagenLogin;
    private javax.swing.JLabel LogoLogin;
    private Controles_Personalizados.Paneles.PanelRound PanelContenedorCampos;
    private Controles_Personalizados.Paneles.PanelRound PanelFondo;
    private javax.swing.JLabel btnCerrar;
    private Controles_Personalizados.Botones.ButtonGradient btnConocerMas;
    private Controles_Personalizados.Botones.ButtonGradient btnLogin;
    private javax.swing.JLabel btnMinimizar;
    private javax.swing.JLabel lblOlvide;
    private javax.swing.JLabel textologin;
    private Controles_Personalizados.textfields.PasswordField txtcontra;
    private Controles_Personalizados.textfields.TextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
