/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import com.sun.awt.AWTUtilities;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;

/**
 *
 * @author danlo
 */
public class FrmP_U_Usuario extends javax.swing.JFrame {

    /**
     * Creates new form PrimerUsoUsuario
     */
    public FrmP_U_Usuario() {
        initComponents();
        this.setLocationRelativeTo(null); 
         Shape forma= new RoundRectangle2D.Double(0,0, this.getBounds() .width, this.getBounds() .height,40,40);
         AWTUtilities. setWindowShape(this, forma);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondo = new Controles_Personalizados.Paneles.PanelRound();
        PanelContenedorCampos = new Controles_Personalizados.Paneles.PanelRound();
        txtUsuario = new Controles_Personalizados.textfields.TextField();
        txtContraseña = new Controles_Personalizados.textfields.TextField();
        txtPIN = new Controles_Personalizados.textfields.TextField();
        CmbEstado = new Controles_Personalizados.ComboBox.combobox();
        CmbTipo = new Controles_Personalizados.ComboBox.combobox();
        btnContinuar = new Controles_Personalizados.Botones.ButtonGradient();
        btnMinimizar = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JLabel();
        Imagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelFondo.setBackground(new java.awt.Color(42, 36, 56));
        PanelFondo.setPreferredSize(new java.awt.Dimension(1366, 768));
        PanelFondo.setRoundBottomLeft(40);
        PanelFondo.setRoundBottomRight(40);
        PanelFondo.setRoundTopLeft(40);
        PanelFondo.setRoundTopRight(40);
        PanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelContenedorCampos.setBackground(new java.awt.Color(254, 254, 254));
        PanelContenedorCampos.setPreferredSize(new java.awt.Dimension(698, 768));
        PanelContenedorCampos.setRoundBottomLeft(35);
        PanelContenedorCampos.setRoundTopLeft(35);
        PanelContenedorCampos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsuario.setBackground(new java.awt.Color(254, 254, 254));
        txtUsuario.setForeground(new java.awt.Color(42, 36, 56));
        txtUsuario.setCaretColor(new java.awt.Color(42, 36, 56));
        txtUsuario.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        txtUsuario.setLabelText("Nombre - usuario");
        txtUsuario.setLineColor(new java.awt.Color(42, 36, 56));
        txtUsuario.setSelectionColor(new java.awt.Color(58, 50, 75));
        PanelContenedorCampos.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 310, 70));

        txtContraseña.setBackground(new java.awt.Color(254, 254, 254));
        txtContraseña.setForeground(new java.awt.Color(42, 36, 56));
        txtContraseña.setCaretColor(new java.awt.Color(42, 36, 56));
        txtContraseña.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        txtContraseña.setLabelText("Contraseña");
        txtContraseña.setLineColor(new java.awt.Color(42, 36, 56));
        txtContraseña.setSelectionColor(new java.awt.Color(58, 50, 75));
        PanelContenedorCampos.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 310, 70));

        txtPIN.setBackground(new java.awt.Color(254, 254, 254));
        txtPIN.setForeground(new java.awt.Color(42, 36, 56));
        txtPIN.setCaretColor(new java.awt.Color(42, 36, 56));
        txtPIN.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        txtPIN.setLabelText("PIN (Combinacion Propia)");
        txtPIN.setLineColor(new java.awt.Color(42, 36, 56));
        txtPIN.setSelectionColor(new java.awt.Color(58, 50, 75));
        PanelContenedorCampos.add(txtPIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 310, 70));

        CmbEstado.setBackground(new java.awt.Color(254, 254, 254));
        CmbEstado.setForeground(new java.awt.Color(42, 36, 56));
        CmbEstado.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        CmbEstado.setLabeText("Estado - Usuario");
        CmbEstado.setLineColor(new java.awt.Color(42, 36, 56));
        PanelContenedorCampos.add(CmbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 540, 310, 80));

        CmbTipo.setBackground(new java.awt.Color(254, 254, 254));
        CmbTipo.setForeground(new java.awt.Color(42, 36, 56));
        CmbTipo.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        CmbTipo.setLabeText("Tipo - Usuario");
        CmbTipo.setLineColor(new java.awt.Color(42, 36, 56));
        PanelContenedorCampos.add(CmbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 310, 80));

        btnContinuar.setText("Continuar");
        btnContinuar.setColor1(new java.awt.Color(42, 36, 56));
        btnContinuar.setColor2(new java.awt.Color(42, 36, 56));
        btnContinuar.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });
        PanelContenedorCampos.add(btnContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 710, 150, -1));

        PanelFondo.add(PanelContenedorCampos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/MinimizarLogin.png"))); // NOI18N
        PanelFondo.add(btnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 20, -1, -1));

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/CerrarLogin.png"))); // NOI18N
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCerrarMousePressed(evt);
            }
        });
        PanelFondo.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 20, -1, -1));

        Imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/UserImg.png"))); // NOI18N
        PanelFondo.add(Imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 140, -1, -1));

        getContentPane().add(PanelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        // TODO add your handling code here:
        FrmLogin log = new FrmLogin();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnContinuarActionPerformed

    private void btnCerrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMousePressed
        System.exit(0);
    }//GEN-LAST:event_btnCerrarMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmP_U_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmP_U_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmP_U_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmP_U_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmP_U_Usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Controles_Personalizados.ComboBox.combobox CmbEstado;
    private Controles_Personalizados.ComboBox.combobox CmbTipo;
    private javax.swing.JLabel Imagen;
    private Controles_Personalizados.Paneles.PanelRound PanelContenedorCampos;
    private Controles_Personalizados.Paneles.PanelRound PanelFondo;
    private javax.swing.JLabel btnCerrar;
    private Controles_Personalizados.Botones.ButtonGradient btnContinuar;
    private javax.swing.JLabel btnMinimizar;
    private Controles_Personalizados.textfields.TextField txtContraseña;
    private Controles_Personalizados.textfields.TextField txtPIN;
    private Controles_Personalizados.textfields.TextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
