/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import com.sun.awt.AWTUtilities;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;

/**
 *
 * @author danlo
 */
public class FrmP_U_Personal extends javax.swing.JFrame {

    /**
     * Creates new form PrimerUsoPersonal
     */
    public FrmP_U_Personal() {
        initComponents();
        this.setLocationRelativeTo(null); 
         Shape forma= new RoundRectangle2D.Double(0,0, this.getBounds() .width, this.getBounds() .height,40,40);
         AWTUtilities. setWindowShape(this, forma);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondo = new Controles_Personalizados.Paneles.PanelRound();
        Logo = new Controles_Personalizados.Paneles.PanelRound();
        btnContinuar = new Controles_Personalizados.Botones.ButtonGradient();
        btnExaminar = new Controles_Personalizados.Botones.ButtonGradient();
        PanelFt = new Controles_Personalizados.Paneles.PanelRound();
        lblLogo = new javax.swing.JLabel();
        txtDocumento = new Controles_Personalizados.textfields.TextField();
        txtNombre = new Controles_Personalizados.textfields.TextField();
        txtApellido = new Controles_Personalizados.textfields.TextField();
        txtCorreo = new Controles_Personalizados.textfields.TextField();
        txtDirecion = new Controles_Personalizados.textfields.TextField();
        CmbGenero = new Controles_Personalizados.ComboBox.combobox();
        CmbTipoPersonal = new Controles_Personalizados.ComboBox.combobox();
        btnMinimizar = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JLabel();
        Imagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelFondo.setBackground(new java.awt.Color(42, 36, 56));
        PanelFondo.setPreferredSize(new java.awt.Dimension(1366, 768));
        PanelFondo.setRoundBottomLeft(40);
        PanelFondo.setRoundBottomRight(40);
        PanelFondo.setRoundTopLeft(40);
        PanelFondo.setRoundTopRight(40);
        PanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setBackground(new java.awt.Color(254, 254, 254));
        Logo.setPreferredSize(new java.awt.Dimension(698, 768));
        Logo.setRoundBottomLeft(35);
        Logo.setRoundTopLeft(35);
        Logo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnContinuar.setText("Continuar");
        btnContinuar.setToolTipText("");
        btnContinuar.setColor1(new java.awt.Color(42, 36, 56));
        btnContinuar.setColor2(new java.awt.Color(42, 36, 56));
        btnContinuar.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });
        Logo.add(btnContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 710, 150, -1));

        btnExaminar.setText("Examinar");
        btnExaminar.setToolTipText("");
        btnExaminar.setColor1(new java.awt.Color(42, 36, 56));
        btnExaminar.setColor2(new java.awt.Color(42, 36, 56));
        btnExaminar.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        Logo.add(btnExaminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 420, 150, -1));

        PanelFt.setBackground(new java.awt.Color(254, 254, 254));
        PanelFt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(42, 36, 56), 2));
        PanelFt.setPreferredSize(new java.awt.Dimension(154, 192));
        Logo.add(PanelFt, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, -1, -1));

        lblLogo.setFont(new java.awt.Font("Roboto Thin", 0, 18)); // NOI18N
        lblLogo.setForeground(new java.awt.Color(91, 91, 95));
        lblLogo.setText("Foto (Opcional)");
        Logo.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, -1, -1));

        txtDocumento.setBackground(new java.awt.Color(254, 254, 254));
        txtDocumento.setForeground(new java.awt.Color(42, 36, 56));
        txtDocumento.setCaretColor(new java.awt.Color(42, 36, 56));
        txtDocumento.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        txtDocumento.setLabelText("Documento (DUI)");
        txtDocumento.setLineColor(new java.awt.Color(42, 36, 56));
        txtDocumento.setSelectionColor(new java.awt.Color(58, 50, 75));
        txtDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDocumentoActionPerformed(evt);
            }
        });
        Logo.add(txtDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 310, 70));

        txtNombre.setBackground(new java.awt.Color(254, 254, 254));
        txtNombre.setForeground(new java.awt.Color(42, 36, 56));
        txtNombre.setCaretColor(new java.awt.Color(42, 36, 56));
        txtNombre.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        txtNombre.setLabelText("Nombres");
        txtNombre.setLineColor(new java.awt.Color(42, 36, 56));
        txtNombre.setSelectionColor(new java.awt.Color(58, 50, 75));
        Logo.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 310, 70));

        txtApellido.setBackground(new java.awt.Color(254, 254, 254));
        txtApellido.setForeground(new java.awt.Color(42, 36, 56));
        txtApellido.setCaretColor(new java.awt.Color(42, 36, 56));
        txtApellido.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        txtApellido.setLabelText("Apellidos");
        txtApellido.setLineColor(new java.awt.Color(42, 36, 56));
        txtApellido.setSelectionColor(new java.awt.Color(58, 50, 75));
        Logo.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 310, 70));

        txtCorreo.setBackground(new java.awt.Color(254, 254, 254));
        txtCorreo.setForeground(new java.awt.Color(42, 36, 56));
        txtCorreo.setToolTipText("");
        txtCorreo.setCaretColor(new java.awt.Color(42, 36, 56));
        txtCorreo.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        txtCorreo.setLabelText("Correo Electronico");
        txtCorreo.setLineColor(new java.awt.Color(42, 36, 56));
        txtCorreo.setSelectionColor(new java.awt.Color(58, 50, 75));
        Logo.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 310, 70));

        txtDirecion.setBackground(new java.awt.Color(254, 254, 254));
        txtDirecion.setForeground(new java.awt.Color(42, 36, 56));
        txtDirecion.setCaretColor(new java.awt.Color(42, 36, 56));
        txtDirecion.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        txtDirecion.setLabelText("Direccion");
        txtDirecion.setLineColor(new java.awt.Color(42, 36, 56));
        txtDirecion.setSelectionColor(new java.awt.Color(58, 50, 75));
        Logo.add(txtDirecion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 310, 70));

        CmbGenero.setBackground(new java.awt.Color(254, 254, 254));
        CmbGenero.setForeground(new java.awt.Color(42, 36, 56));
        CmbGenero.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        CmbGenero.setLabeText("Genero");
        CmbGenero.setLineColor(new java.awt.Color(42, 36, 56));
        Logo.add(CmbGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 610, 310, 80));

        CmbTipoPersonal.setBackground(new java.awt.Color(254, 254, 254));
        CmbTipoPersonal.setForeground(new java.awt.Color(42, 36, 56));
        CmbTipoPersonal.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        CmbTipoPersonal.setLabeText("Tipo - Personal");
        CmbTipoPersonal.setLineColor(new java.awt.Color(42, 36, 56));
        Logo.add(CmbTipoPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 510, 310, 80));

        PanelFondo.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/MinimizarLogin.png"))); // NOI18N
        PanelFondo.add(btnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 20, -1, -1));

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/CerrarLogin.png"))); // NOI18N
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCerrarMousePressed(evt);
            }
        });
        PanelFondo.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 20, -1, -1));

        Imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/PersonalImg.png"))); // NOI18N
        PanelFondo.add(Imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 140, -1, -1));

        getContentPane().add(PanelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        // TODO add your handling code here:
        FrmP_U_Usuario pu = new FrmP_U_Usuario();
        pu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnContinuarActionPerformed

    private void txtDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocumentoActionPerformed

    private void btnCerrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMousePressed
        System.exit(0);
    }//GEN-LAST:event_btnCerrarMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmP_U_Personal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmP_U_Personal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmP_U_Personal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmP_U_Personal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmP_U_Personal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Controles_Personalizados.ComboBox.combobox CmbGenero;
    private Controles_Personalizados.ComboBox.combobox CmbTipoPersonal;
    private javax.swing.JLabel Imagen;
    private Controles_Personalizados.Paneles.PanelRound Logo;
    private Controles_Personalizados.Paneles.PanelRound PanelFondo;
    private Controles_Personalizados.Paneles.PanelRound PanelFt;
    private javax.swing.JLabel btnCerrar;
    private Controles_Personalizados.Botones.ButtonGradient btnContinuar;
    private Controles_Personalizados.Botones.ButtonGradient btnExaminar;
    private javax.swing.JLabel btnMinimizar;
    private javax.swing.JLabel lblLogo;
    private Controles_Personalizados.textfields.TextField txtApellido;
    private Controles_Personalizados.textfields.TextField txtCorreo;
    private Controles_Personalizados.textfields.TextField txtDirecion;
    private Controles_Personalizados.textfields.TextField txtDocumento;
    private Controles_Personalizados.textfields.TextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
